### ISSUE TITLE
Questions: How define the planning horizon/tree height? Is it possible to get all actions from the branch with the most reward?

### ISSUE THREAD

**Issue by autonomobil** [AdaCompNUS/despot#13]
Let's say we a have a POMDP model with 9 actions, as well as a continuous state space. 

* First question: How define the planning horizon/tree height by using DESPOT with the cpp model?

* Second question: Is there a possibility to get all actions which are on the highest rewarded branch?

To make things a bit clearer:  This shows a planning horizon of 2 (two actions), correct? 
![image](https://user-images.githubusercontent.com/31781343/72777585-7b12d400-3c16-11ea-8007-2079c3ec91f5.png)

Let's say the yellow branch has the highest reward, now I want an array with [a2, a2]. Is this possible?

**Comment by autonomobil** [comment]
Ahh, `Globals::config.sim_len`  seems to be my wanted variable 

And in[ Running the Planning ](https://github.com/AdaCompNUS/despot/blob/API_redesign/doc/cpp_model_doc/Tutorial%20on%20Using%20DESPOT%20with%20cpp%20model.md#4-running-the-planning)it becomes clear how to get the actions

**Comment by cindycia** [comment]
> Ahh, `Globals::config.search_depth` seems to be my wanted variable, correct? Found in[ Running the Planning ](https://github.com/AdaCompNUS/despot/blob/API_redesign/doc/cpp_model_doc/Tutorial%20on%20Using%20DESPOT%20with%20cpp%20model.md#4-running-the-planning).
> 
> So there is still the question on how to get all actions from that branch..

Yes, `Globals::config.search_depth` is the correct flag. You can find the descriptions of all global flags [here](https://github.com/AdaCompNUS/despot/blob/API_redesign/include/despot/config.h).

For retrieving the optimal policy tree (instead of the single action at the root), you can adapt from the `PrintPolicyTree` function in [node.cpp](https://github.com/AdaCompNUS/despot/blob/API_redesign/src/core/node.cpp). This function prints the optimal policy tree under a node.
