### ISSUE TITLE
POS_INFTY and NEG_INFTY are not infinite

### ISSUE THREAD

**Issue by mkoval** [AdaCompNUS/despot#5]
The constants are currently defined as:
```c++
const double POS_INFTY = numeric_limits<double>::max();
const double NEG_INFTY = -POS_INFTY;
```
However, [`numeric_limits<>::max` is defined to be](http://en.cppreference.com/w/cpp/types/numeric_limits/max):

> Returns the maximum finite value representable by the numeric type T.

It would make more sense to use [`numeric_limits<double>::infinity()`](http://en.cppreference.com/w/cpp/types/numeric_limits/infinity). I would be happy to make a pull request for this change. However, I want to check:

Is `max()` used instead of `infinity()` here intentionally? I.e. will something break if I make this change?

**Comment by yenan** [comment]
hi Michael,

max() was used because on platforms not following the IEEE 754
<http://en.cppreference.com/w/cpp/types/numeric_limits/is_iec559> standard,
infinity() is not meaningful.

in case you need to use infinity() to make things work, i've modified the
definition so that whenever infinity() is meaningful, POS_INFTY is
infinity().

- Nan
